apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
spec:
  volumes:
    - name: "pgdata"
      hostPath:
        path: "/home/docker/pgdata"
  containers:
    - image: postgres:14
      name: postgresql
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: "pgdata"
