apiVersion: v1
kind: Pod
metadata:
  name: rust-webapp
spec:
  containers:
    - image: ghcr.io/t0m0h1de/rust-webapp-sample/rust-webapp-sample:latest
      name: rust-webapp
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
