apiVersion: v1
kind: Pod
metadata:
  name: toggle-health-app
spec:
  containers:
    - image: ghcr.io/t0m0h1de/wildfly-toggle-health-app/toggle-health-app:latest
      name: toggle-health-app
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP